org: ramanand87
app: mail
service: send-mail

custom:
  wsgi:
    app: app.app
    packRequirements: false
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: send-email
          method: post

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - __pycache__/**

# custom: